### ISSUE TITLE
Transport Error

### ISSUE THREAD

**Issue by gemlabsdev** [metaapi/metaapi-javascript-sdk#1]
Hi, occasionally I get this transport error on the console. 

2023-11-21T05:58:56.611218+00:00 app[web.1]: [2023-11-21T05:58:56.611Z] new-york:0: MetaApi websocket client disconnected from the MetaApi server because of transport close
2023-11-21T05:58:57.427599+00:00 app[web.1]: [2023-11-21T05:58:57.425Z] new-york:0: MetaApi websocket client connection error Error: xhr poll error
2023-11-21T05:58:57.427612+00:00 app[web.1]: at Transport.onError (/app/node_modules/engine.io-client/lib/transport.js:68:13)
2023-11-21T05:58:57.427612+00:00 app[web.1]: at Request.<anonymous> (/app/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
2023-11-21T05:58:57.427613+00:00 app[web.1]: at Emitter.emit (/app/node_modules/component-emitter/index.js:145:20)
2023-11-21T05:58:57.427613+00:00 app[web.1]: at Request.onError (/app/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
2023-11-21T05:58:57.427613+00:00 app[web.1]: at Timeout._onTimeout (/app/node_modules/engine.io-client/lib/transports/polling-xhr.js:261:18)
2023-11-21T05:58:57.427614+00:00 app[web.1]: at listOnTimeout (node:internal/timers:573:17)
2023-11-21T05:58:57.427614+00:00 app[web.1]: at process.processTimers (node:internal/timers:514:7) {
2023-11-21T05:58:57.427615+00:00 app[web.1]: type: 'TransportError',
2023-11-21T05:58:57.427616+00:00 app[web.1]: description: 502
2023-11-21T05:58:57.427616+00:00 app[web.1]: }

Obviously the request fails, however all subsequent requests seem to work fine until we reach another failure. Do you have any idea what might be causing this?

**Comment by metaapi** [comment]
Closing the ticked due to no response. Feel free to send a follow-up message if this issue is still actual.

**Comment by gemlabsdev** [comment]
Hi, I apologize for the late response. It turns our that the issue had been caused by a hanging open connection if two or more concurrent calls were made though my server application. I haven't run into any Transport Errors since.
